version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

workflows:
  main:
    jobs:
      - unit-test

jobs:
  unit-test:
    executor:
        name: default
    steps:
      - checkout
      - restore_cache:
          key: podder-task-base-dependency-cache-{{ checksum "pyproject.toml" }}
      - run:
          name: Install requirements
          command: |
            pip install -U pip poetry setuptools

            poetry install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "pyproject.toml" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run pytest
          command: |
            poetry run pytest tests/
