# Please set the environment variables:
# - AWS_REGION
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - ECR_REPOSITORY
# - IMAGES_YML_S3_URI
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-s3: circleci/aws-s3@2.0.0

executors:
  default:
    docker:
      - image: circleci/python:3.8

workflows:
  unit-test:
    jobs:
      - unit-test
  build-and-push-image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${ECR_REPOSITORY}"
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - dev
                - stg
                - production
      - update-argo:
          requires:
            - aws-ecr/build-and-push-image

jobs:
  unit-test:
    executor:
        name: default
    steps:
      - checkout
      - run:
          name: Custom Settings
          command: |
            # ========== Custom Settings ==========
            # Please install the libraries if necessary.
            # For example: "sudo apt-get update && sudo apt-get install -y curl"
            #
            # ========== END ==========
      - restore_cache:
          key: podder-task-base-dependency-cache-{{ checksum "pyproject.toml" }}
      - run:
          name: Install requirements
          command: |
            pip install -U pip poetry setuptools
            poetry install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "pyproject.toml" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run pytest
          command: |
            poetry run pytest tests/

  update-argo:
    executor:
      name: default
    steps:
      - checkout
      - aws-s3/copy:
          from: ${IMAGES_YML_S3_URI}
          to: images.yml
      - run:
          name: Update Images Yaml
          command: |
            pip install -U pip setuptools PyYAML
            export FILE=update-file.py

            echo "import yaml;
            with open('images.yml') as f: images = yaml.safe_load(f.read());
            print(f'images (before): {images}')
            images['starter-task-image'] = '099280104478.dkr.ecr.us-west-1.amazonaws.com/${ECR_REPOSITORY}:${CIRCLE_SHA1}';
            print(f'images (after): {images}')
            with open('images.yml', 'w') as f: f.write(yaml.dump(images));" >> $FILE

            python $FILE
            echo "Successfully updated the images.yml."
      - aws-s3/copy:
          from: images.yml
          to: ${IMAGES_YML_S3_URI}
